apoca/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from pacientes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # TODO: remover linha abaixo apos criar sistema de login completo
    path('accounts/login/', auth_views.LoginView.as_view(template_name='admin/login.html')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pacientes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pacientes/urls.py
from django.urls import path
from . import views

app_name = 'pacientes'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('pacientes/', views.pacientes, name='pacientes'),
    path('paciente/cadastrar/', views.cadastrar_paciente, name='cadastrar_paciente'),
    path('paciente/<int:pk>/editar/', views.editar_paciente, name='editar_paciente'),
    path('paciente/<int:pk>/perfil_paciente', views.perfil_paciente, name='perfil_paciente'),
    path('paciente/<int:pk>/consultas/cadastrar/', views.cadastrar_consulta, name='cadastrar_consulta'),
    path('paciente/<int:pk>/consultas/editar/', views.editar_consulta, name='editar_consulta'),
    path('paciente/<int:pk>/exames/cadastrar/', views.cadastrar_exame, name='cadastrar_exame'),
    path('paciente/<int:pk>/exames/editar/', views.editar_exame, name='editar_exame'),
    path('paciente/<int:pk>/auxilio/cadastrar/', views.cadastrar_auxilio, name='cadastrar_auxilio'),
    path('paciente/<int:pk>/auxilio/editar/', views.editar_auxilio, name='editar_auxilio'),

    path('auxilios/', views.listar_auxilios, name='listar_auxilios'),
    path('auxilios/equipamentos_emprestados', views.listar_equipamentos_emprestados, name='listar_equipamentos_emprestados'),
    path('auxilios/<int:pk>/registrar_devolucao', views.registrar_devolucao, name='registrar_devolucao'),
    path('auxilios/<int:pk>/renovar_emprestimo', views.renovar_emprestimo, name='renovar_emprestimo'),
    path('auxilios/<int:pk>/detalhes_auxilio', views.detalhes_auxilio, name='detalhes_auxilio'),

    # URLS ajax
    path('paciente/<int:pk>/remover_foto', views.remover_foto, name='remover_foto'),
    path('paciente/<int:pk>/filtrar_auxilios', views.filtrar_auxilios, name='filtrar_auxilios'),
    path('filtrar_info_gerais/', views.filtrar_info_gerais, name='filtrar_info_gerais'),

    # URL administrativo
    path('administrativo/', views.administrativo, name='administrativo'),
    path('administrativo/backup/', views.backup, name='backup'),

    # URL apresentação equipe
    path('equipe/', views.equipe, name='equipe'),

    # Cadastros gerais
    path('cadastros-gerais/medicamento/', views.medicamentos, name='medicamentos'),
    path('cadastros-gerais/medicamento/cadastrar/', views.cadastrar_medicamento, name='cadastrar_medicamento'),
    path('cadastros-gerais/medicamento/<int:pk>/editar/', views.editar_medicamento, name='editar_medicamento'),
    path('cadastros-gerais/equipamento/', views.equipamentos, name='equipamentos'),
    path('cadastros-gerais/equipamento/cadastrar/', views.cadastrar_equipamento, name='cadastrar_equipamento'),
    path('cadastros-gerais/equipamento/<int:pk>/editar/', views.editar_equipamento, name='editar_equipamento'),
    path('cadastros-gerais/tipo-auxilio/', views.tipos_auxilios, name='tipos_auxilios'),
    path('cadastros-gerais/tipo-auxilio/cadastrar/', views.cadastrar_tipo_auxilio, name='cadastrar_tipo_auxilio'),
    path('cadastros-gerais/tipo-auxilio/<int:pk>/editar/', views.editar_tipo_auxilio, name='editar_tipo_auxilio'),
    path('cadastros-gerais/cidade/', views.cidades, name='cidades'),
    path('cadastros-gerais/cidade/cadastrar/', views.cadastrar_cidade, name='cadastrar_cidade'),
    path('cadastros-gerais/cidade/<int:pk>/editar/', views.editar_cidade, name='editar_cidade'),
    path('cadastros-gerais/tipo-consulta/', views.tipos_consulta, name='tipos_consulta'),
    path('cadastros-gerais/tipo-consulta/cadastrar/', views.cadastrar_tipo_consulta, name='cadastrar_tipo_consulta'),
    path('cadastros-gerais/tipo-consulta/<int:pk>/editar/', views.editar_tipo_consulta, name='editar_tipo_consulta'),
    path('cadastros-gerais/doenca/', views.doencas, name='doencas'),
    path('cadastros-gerais/doenca/cadastrar/', views.cadastrar_doenca, name='cadastrar_doenca'),
    path('cadastros-gerais/doenca/<int:pk>/editar/', views.editar_doenca, name='editar_doenca'),
    path('cadastros-gerais/suplemento-alimentar/', views.sup_alimentares, name='sup_alimentares'),
    path('cadastros-gerais/suplemento-alimentar/cadastrar/', views.cadastrar_sup_alimentar, name='cadastrar_sup_alimentar'),
    path('cadastros-gerais/suplemento-alimentar/<int:pk>/editar/', views.editar_sup_alimentar, name='editar_sup_alimentar'),

    # Consulta
    path('consultas/', views.consultas, name='consultas'),

    # Exame
    path('exames/', views.exames, name='exames'),
]

pacientes/views/cadastros_gerais.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages

from ..decorators import *
from ..models import *
from ..forms import *


@assistente_social_required
@login_required
def medicamentos(request):
    if request.method == 'POST':
        try:
            medicamento = get_object_or_404(Medicamento, pk=request.POST['pk'])
            medicamento.delete()
        except Exception:
            messages.error(request, 'O medicamento não pode ser deletado pois tem relação com um ou mais pacientes.')
        else:
            messages.success(request, 'Medicamento excluído com sucesso!')

    medicamentos = Medicamento.objects.all()
    return render(request, 'cadastros_gerais/medicamento/medicamento.html', {'medicamentos': medicamentos})


@assistente_social_required
@login_required
def cadastrar_medicamento(request):
    form = FormMedicamento(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            medicamento_repetido = Medicamento.objects.filter(nome=form.cleaned_data['nome'])
            if medicamento_repetido:
                messages.error(request, 'O medicamento informado já existe.')
            else:
                form.save()
                messages.success(request, 'Medicamento cadastrado com sucesso!')
                return redirect('pacientes:medicamentos')

    return render(request, 'cadastros_gerais/medicamento/cadastro_medicamento.html', {'form': form})


@assistente_social_required
@login_required
def editar_medicamento(request, pk):
    medicamento = get_object_or_404(Medicamento, pk=pk)
    nome = medicamento.nome

    if request.method == 'POST':
        form = FormMedicamento(request.POST, instance=medicamento)
        if form.is_valid():
            medicamento_repetido = Medicamento.objects.filter(nome=form.cleaned_data['nome'])

            if medicamento_repetido and medicamento_repetido[0].nome == form.cleaned_data['nome'] and nome != form.cleaned_data['nome'] :
                messages.error(request, 'O medicamento informado já existe.')
            else:
                form.save()
                messages.success(request, 'Medicamento editado com sucesso!')
                return redirect('pacientes:medicamentos')
    else:
        form = FormMedicamento(instance=medicamento)

    return render(request, 'cadastros_gerais/medicamento/edicao_medicamento.html', {'form': form})


@assistente_social_required
@login_required
def equipamentos(request):
    if request.method == 'POST':
        try:
            equipamento = get_object_or_404(Equipamento, pk=request.POST['pk'])
            equipamento.delete()
        except Exception:
            messages.error(request, 'O equipamento não pode ser deletado pois tem relação com um ou mais pacientes.')
        else:
            messages.success(request, 'Equipamento excluído com sucesso!')

    equipamentos = Equipamento.objects.all()
    return render(request, 'cadastros_gerais/equipamento/equipamento.html', {'equipamentos': equipamentos})


@assistente_social_required
@login_required
def cadastrar_equipamento(request):
    form = FormEquipamento(request.POST or None or request.GET)
    formulario = FormEquipamento()

    if request.method == 'POST' or request.method == 'GET':
        if form.is_valid():
            equipamento_repetido = Equipamento.objects.filter(etiqueta=form.cleaned_data['etiqueta'])
            if equipamento_repetido:
                messages.error(request, 'A etiqueta informada já foi cadastrada.')
            else:
                form.save()
                messages.success(request, 'Equipamento cadastrado com sucesso!')
                return redirect('pacientes:equipamentos')

    return render(request=request,context={'form': formulario} ,template_name='cadastros_gerais/equipamento/cadastro_equipamento.html')


@assistente_social_required
@login_required
def editar_equipamento(request, pk):
    equipamento = get_object_or_404(Equipamento, pk=pk)
    etiqueta = equipamento.etiqueta

    if request.method == 'POST':
        form = FormEquipamento(request.POST, instance=equipamento)
        if form.is_valid():
            equipamento_repetido = Equipamento.objects.filter(etiqueta=form.cleaned_data['etiqueta'])

            if equipamento_repetido and equipamento_repetido[0].etiqueta == form.cleaned_data['etiqueta'] and form.cleaned_data['etiqueta'] != etiqueta:
                messages.error(request, 'O equipamento informado já existe.')
            else:
                form.save()
                messages.success(request, 'Equipamento editado com sucesso!')
                return redirect('pacientes:equipamentos')
    else:
        form = FormEquipamento(instance=equipamento)

    return render(request, 'cadastros_gerais/equipamento/edicao_equipamento.html', {'form': form})


@assistente_social_required
@login_required
def tipos_auxilios(request):
    if request.method == 'POST':
        try:
            tipo_auxilio = get_object_or_404(TipoAuxilio, pk=request.POST['pk'])
            tipo_auxilio.delete()
        except Exception:
            messages.error(request, 'O tipo de auxílio não pode ser deletado pois tem relação com um ou mais pacientes.')
        else:
            messages.success(request, 'Tipo de auxílio excluído com sucesso!')

    tipo_auxilios = TipoAuxilio.objects.all()
    return render(request, 'cadastros_gerais/tipo_auxilio/tipo_auxilio.html', {'tipos_auxilios': tipo_auxilios})


@assistente_social_required
@login_required
def cadastrar_tipo_auxilio(request):
    form = FormTipoAuxilio(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            auxilio_repetido = TipoAuxilio.objects.filter(nome=form.cleaned_data['nome'])
            if auxilio_repetido:
                messages.error(request, 'O tipo de auxílio informado já foi cadastrado.')
            else:
                form.save()
                messages.success(request, 'Tipo de auxílio cadastrado com sucesso!')
                return redirect('pacientes:tipos_auxilios')

    return render(request, 'cadastros_gerais/tipo_auxilio/cadastro_tipo_auxilio.html', {'form': form})


@assistente_social_required
@login_required
def editar_tipo_auxilio(request, pk):
    tipo_auxilio = get_object_or_404(TipoAuxilio, pk=pk)
    nome = tipo_auxilio.nome

    if request.method == 'POST':
        form = FormTipoAuxilio(request.POST, instance=tipo_auxilio)
        if form.is_valid():
            tipo_auxilio_repetido = TipoAuxilio.objects.filter(nome=form.cleaned_data['nome'])

            if tipo_auxilio_repetido and tipo_auxilio_repetido[0].nome == form.cleaned_data['nome'] and form.cleaned_data['nome'] != nome:
                messages.error(request, 'O tipo de auxílio informado já existe.')
            else:
                form.save()
                messages.success(request, 'Tipo de auxílio editado com sucesso!')
                return redirect('pacientes:tipos_auxilios')
    else:
        form = FormTipoAuxilio(instance=tipo_auxilio)

    return render(request, 'cadastros_gerais/tipo_auxilio/edicao_tipo_auxilio.html', {'form': form})


@assistente_social_required
@login_required
def cidades(request):
    if request.method == 'POST':
        try:
            cidade = get_object_or_404(Cidade, pk=request.POST['pk'])
            cidade.delete()
        except Exception:
            messages.error(request, 'A cidade não pode ser deletado pois tem relação com um ou mais pacientes.')
        else:
            messages.success(request, 'Cidade excluída com sucesso!')

    cidades = Cidade.objects.all()
    return render(request, 'cadastros_gerais/cidade/cidade.html', {'cidades': cidades})


@assistente_social_required
@login_required
def cadastrar_cidade(request):
    form = FormCidade(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            cidade_repetida = Cidade.objects.filter(nome=form.cleaned_data['nome'])
            if cidade_repetida:
                messages.error(request, 'A cidade informada já foi cadastrada.')
            else:
                form.save()
                messages.success(request, 'Cidade cadastrada com sucesso!')
                return redirect('pacientes:cidades')

    return render(request, 'cadastros_gerais/cidade/cadastro_cidade.html', {'form': form})


@assistente_social_required
@login_required
def editar_cidade(request, pk):
    cidade = get_object_or_404(Cidade, pk=pk)
    nome = cidade.nome

    if request.method == 'POST':
        form = FormCidade(request.POST, instance=cidade)
        if form.is_valid():
            cidade_repetida = Cidade.objects.filter(nome=form.cleaned_data['nome'])

            if cidade_repetida and cidade_repetida[0].nome == form.cleaned_data['nome'] and form.cleaned_data['nome'] != nome:
                messages.error(request, 'A cidade informada já existe.')
            else:
                form.save()
                messages.success(request, 'Cidade editada com sucesso!')
                return redirect('pacientes:cidades')
    else:
        form = FormCidade(instance=cidade)

    return render(request, 'cadastros_gerais/cidade/edicao_cidade.html', {'form': form})


@assistente_social_required
@login_required
def tipos_consulta(request):
    if request.method == 'POST':
        try:
            tipo_consulta = get_object_or_404(TipoConsulta, pk=request.POST['pk'])
            tipo_consulta.delete()
        except Exception:
            messages.error(request, 'O tipo de consulta não pode ser deletado pois tem relação com um ou mais pacientes.')
        else:
            messages.success(request, 'Tipo de consulta excluído com sucesso!')

    tipos_consulta = TipoConsulta.objects.all()
    return render(request, 'cadastros_gerais/tipo_consulta/tipo_consulta.html', {'tipos_consulta': tipos_consulta})


@assistente_social_required
@login_required

templates/cadastros_gerais/medicamento/cadastro_medicamento.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    <title>APOCA - Cadastro de Medicamento</title>
{% endblock %}

{% block content %}
    {% include 'utilitarios/mensagens.html' %}
    
    <div class="card card-body">
        <h2 class="mb-3">Cadastro de medicamento</h2>
        {% crispy form %}
    </div>

    {% include 'utilitarios/modal_cancelamento.html' %}

{% endblock %}

templates/cadastros_gerais/medicamento/edicao_medicamento.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    <title>APOCA - Edição de Medicamento</title>
{% endblock %}

{% block content %}
    {% include 'utilitarios/mensagens.html' %}
    
    <div class="card card-body">
        <h2 class="mb-3">Edição de medicamento</h2>
        {% crispy form %}
    </div>

    {% include 'utilitarios/modal_cancelamento.html' %}

{% endblock %}

templates/cadastros_gerais/medicamento/medicamento.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}
    <title>APOCA - Cadastro de Medicamento</title>
{% endblock %}

{% block css %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
    {% include 'utilitarios/mensagens.html' %}

    <div class="card overflow-hidden mb-4">
        {% include 'utilitarios/cabecalho.html' with titulo="Medicamentos" imagem="/static/images/SVG/medicamento.svg" %}

        <div class="card-body">
            <div class="d-flex justify-content-center mb-4">
                <div class="ml-md-auto">
                    <a href="{% url 'pacientes:cadastrar_medicamento' %}" class="btn btn-primary">Cadastrar Medicamento</a>
                </div>
            </div>

            <div class="table-responsive">
                <table class="table table-centered table-nowrap table-hover" id="tabela-medicamento">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">Nome</th>
                            <th scope="col">Ações</th>
                        </tr>
                    </thead>
                    <tbody id="myTable">
                        {% for medicamento in medicamentos %}
                        <tr>
                            <td>{{ medicamento.nome }}</td>
                            <td>
                                <ul class="list-inline font-size-20 contact-links mb-0">
                                    <li class="list-inline-item px-2">
                                        <a href="{% url 'pacientes:editar_medicamento' pk=medicamento.pk %}" data-toggle="tooltip" data-placement="top" title="Editar"><i class="bx bx-edit"></i></a>
                                    </li>
                                    <li class="list-inline-item px-2">
                                        <a
                                            data-toggle="tooltip"
                                            data-placement="top"
                                            title="Excluír"
                                            onclick="abrirModal({{ medicamento.pk }})"
                                        >
                                            <i class="bx bx-trash"></i>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Modal para a deleção -->
    {% include 'utilitarios/modal_delecao.html' %}
{% endblock %}

{% block js %}
    <script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>

    {% include 'utilitarios/configuracao_data_table.html' with tipo="medicamento" %}
{% endblock %}