apoca/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from pacientes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # TODO: remover linha abaixo apos criar sistema de login completo
    path('accounts/login/', auth_views.LoginView.as_view(template_name='admin/login.html')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pacientes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pacientes/urls.py
from django.urls import path
from . import views

app_name = 'pacientes'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('pacientes/', views.pacientes, name='pacientes'),
    path('paciente/cadastrar/', views.cadastrar_paciente, name='cadastrar_paciente'),
    path('paciente/<int:pk>/editar/', views.editar_paciente, name='editar_paciente'),
    path('paciente/<int:pk>/perfil_paciente', views.perfil_paciente, name='perfil_paciente'),
    path('paciente/<int:pk>/consultas/cadastrar/', views.cadastrar_consulta, name='cadastrar_consulta'),
    path('paciente/<int:pk>/consultas/editar/', views.editar_consulta, name='editar_consulta'),
    path('paciente/<int:pk>/exames/cadastrar/', views.cadastrar_exame, name='cadastrar_exame'),
    path('paciente/<int:pk>/exames/editar/', views.editar_exame, name='editar_exame'),
    path('paciente/<int:pk>/auxilio/cadastrar/', views.cadastrar_auxilio, name='cadastrar_auxilio'),
    path('paciente/<int:pk>/auxilio/editar/', views.editar_auxilio, name='editar_auxilio'),

    path('auxilios/', views.listar_auxilios, name='listar_auxilios'),
    path('auxilios/equipamentos_emprestados', views.listar_equipamentos_emprestados, name='listar_equipamentos_emprestados'),
    path('auxilios/<int:pk>/registrar_devolucao', views.registrar_devolucao, name='registrar_devolucao'),
    path('auxilios/<int:pk>/renovar_emprestimo', views.renovar_emprestimo, name='renovar_emprestimo'),
    path('auxilios/<int:pk>/detalhes_auxilio', views.detalhes_auxilio, name='detalhes_auxilio'),

    # URLS ajax
    path('paciente/<int:pk>/remover_foto', views.remover_foto, name='remover_foto'),
    path('paciente/<int:pk>/filtrar_auxilios', views.filtrar_auxilios, name='filtrar_auxilios'),
    path('filtrar_info_gerais/', views.filtrar_info_gerais, name='filtrar_info_gerais'),

    # URL administrativo
    path('administrativo/', views.administrativo, name='administrativo'),
    path('administrativo/backup/', views.backup, name='backup'),

    # URL apresentação equipe
    path('equipe/', views.equipe, name='equipe'),

    # Cadastros gerais
    path('cadastros-gerais/medicamento/', views.medicamentos, name='medicamentos'),
    path('cadastros-gerais/medicamento/cadastrar/', views.cadastrar_medicamento, name='cadastrar_medicamento'),
    path('cadastros-gerais/medicamento/<int:pk>/editar/', views.editar_medicamento, name='editar_medicamento'),
    path('cadastros-gerais/equipamento/', views.equipamentos, name='equipamentos'),
    path('cadastros-gerais/equipamento/cadastrar/', views.cadastrar_equipamento, name='cadastrar_equipamento'),
    path('cadastros-gerais/equipamento/<int:pk>/editar/', views.editar_equipamento, name='editar_equipamento'),
    path('cadastros-gerais/tipo-auxilio/', views.tipos_auxilios, name='tipos_auxilios'),
    path('cadastros-gerais/tipo-auxilio/cadastrar/', views.cadastrar_tipo_auxilio, name='cadastrar_tipo_auxilio'),
    path('cadastros-gerais/tipo-auxilio/<int:pk>/editar/', views.editar_tipo_auxilio, name='editar_tipo_auxilio'),
    path('cadastros-gerais/cidade/', views.cidades, name='cidades'),
    path('cadastros-gerais/cidade/cadastrar/', views.cadastrar_cidade, name='cadastrar_cidade'),
    path('cadastros-gerais/cidade/<int:pk>/editar/', views.editar_cidade, name='editar_cidade'),
    path('cadastros-gerais/tipo-consulta/', views.tipos_consulta, name='tipos_consulta'),
    path('cadastros-gerais/tipo-consulta/cadastrar/', views.cadastrar_tipo_consulta, name='cadastrar_tipo_consulta'),
    path('cadastros-gerais/tipo-consulta/<int:pk>/editar/', views.editar_tipo_consulta, name='editar_tipo_consulta'),
    path('cadastros-gerais/doenca/', views.doencas, name='doencas'),
    path('cadastros-gerais/doenca/cadastrar/', views.cadastrar_doenca, name='cadastrar_doenca'),
    path('cadastros-gerais/doenca/<int:pk>/editar/', views.editar_doenca, name='editar_doenca'),
    path('cadastros-gerais/suplemento-alimentar/', views.sup_alimentares, name='sup_alimentares'),
    path('cadastros-gerais/suplemento-alimentar/cadastrar/', views.cadastrar_sup_alimentar, name='cadastrar_sup_alimentar'),
    path('cadastros-gerais/suplemento-alimentar/<int:pk>/editar/', views.editar_sup_alimentar, name='editar_sup_alimentar'),

    # Consulta
    path('consultas/', views.consultas, name='consultas'),

    # Exame
    path('exames/', views.exames, name='exames'),
]

pacientes/views/auxilios.py
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.forms import ModelChoiceField
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages

from ..decorators import *
from ..models import *
from ..forms import *
from .utilitarios import *


@assistente_social_required
@login_required
def listar_auxilios(request):
    if request.method == 'POST':
        try:
            auxilio = get_object_or_404(Auxilio, pk=request.POST['pk'])
            auxilio.delete()
        except Exception:
            messages.error(request, 'O auxílio não pode ser excluído.')
        else:
            messages.success(request, 'Auxílio excluído com sucesso!')

    lista_auxilios = Auxilio.objects.all().order_by('data_retirada')

    return render(request, 'auxilios/lista_auxilios.html', {'lista_auxilios': lista_auxilios})


@assistente_social_required
@login_required
def cadastrar_auxilio(request, pk):
    form_auxilio = FormAuxilio(request.POST or None)
    form_auxilio.fields['equipamento'] = ModelChoiceField(queryset=Equipamento.objects.filter(emprestado=False))
    print(form_auxilio.fields['equipamento'])
    paciente = get_object_or_404(Paciente, pk=pk)
    if request.method == "POST":
        if form_auxilio.is_valid():
            auxilio = form_auxilio.save(commit=False)
            if str(auxilio.tipo.nome).upper() == 'MEDICAMENTO':
                if auxilio.medicamento is None:
                    messages.error(request, 'Erro. Selecione um medicamento ou altere o tipo do auxílio.')
                    return render(request, 'auxilios/cadastro_auxilio.html', {'form': form_auxilio})
            else:
                auxilio.medicamento = None
            if str(auxilio.tipo.nome).upper() == 'EMPRÉSTIMO DE EQUIPAMENTO':
                if auxilio.equipamento is None:
                    messages.error(request, 'Erro. Selecione um equipamento ou altere o tipo do auxílio.')
                    return render(request, 'auxilios/cadastro_auxilio.html', {'form': form_auxilio})
                else:
                    equipamento = get_object_or_404(Equipamento, pk=auxilio.equipamento.id)
                    if(equipamento.emprestado):
                        messages.error(request, 'Equipamento já está emprestado.')
                        return render(request, 'auxilios/cadastro_auxilio.html', {'form': form_auxilio})
                    else:
                        equipamento.emprestado = True
                        equipamento.save()
            else:
                auxilio.equipamento = None
            
            if str(auxilio.tipo.nome).upper() == 'SUPLEMENTO ALIMENTAR':
                if auxilio.suplemento_alimentar is None:
                    messages.error(request, 'Erro. Selecione um suplemento alimentar ou altere o tipo do auxílio.')
                    return render(request, 'auxilios/cadastro_auxilio.html', {'form': form_auxilio})
            else:
                auxilio.suplemento_alimentar = None

            auxilio.paciente = get_object_or_404(Paciente, pk=pk)
            auxilio.save()

            messages.success(request, 'Auxílio cadastrado com sucesso.')
            return redirect('pacientes:perfil_paciente', pk=auxilio.paciente.pk)

        messages.error(request, 'Não foi possível cadastrar o auxílio.')

    return render(request, 'auxilios/cadastro_auxilio.html', {'form': form_auxilio, 'paciente': paciente})


@assistente_social_required
@login_required
def editar_auxilio(request, pk):
    auxilio = get_object_or_404(Auxilio, pk=pk)
    if request.method == 'POST':
        form_auxilio = FormAuxilio(request.POST, instance=auxilio)
        if form_auxilio.is_valid():
            auxilio = form_auxilio.save(commit=False)
            if str(auxilio.tipo.abreviacao) == 'ME':
                if auxilio.medicamento is None:
                    messages.error(request, 'Erro. Selecione um medicamento ou altere o tipo do auxílio.')
                    return render(request, 'auxilios/edicao_auxilio.html', {'form': form_auxilio})
            else:
                auxilio.medicamento = None
            if str(auxilio.tipo.abreviacao) == 'EE':
                if auxilio.equipamento is None:
                    messages.error(request, 'Erro. Selecione um equipamento ou altere o tipo do auxílio.')
                    return render(request, 'auxilios/edicao_auxilio.html', {'form': form_auxilio})
            else:
                auxilio.equipamento = None

            auxilio.save()

            messages.success(request, 'Auxílio alterado com sucesso.')
            return redirect('pacientes:listar_auxilios')
    else:
        auxilio.data_retirada = None
        auxilio.hora_retirada = None
        form_auxilio = FormAuxilio(instance=auxilio)

    return render(request, 'auxilios/edicao_auxilio.html', {'form': form_auxilio, 'paciente': auxilio.paciente})


@assistente_social_required
@login_required
def listar_equipamentos_emprestados(request):
    equipamentos_emprestados = Auxilio.objects.all().filter(tipo__abreviacao='EE',
        data_devolucao__isnull=True, equipamento__emprestado=True).order_by('-data_retirada')

    return render(request, 'auxilios/equipamentos_emprestados.html', {'equipamentos_emprestados': equipamentos_emprestados})


@assistente_social_required
@login_required
def registrar_devolucao(request, pk):
    auxilio = get_object_or_404(Auxilio, pk=pk)
    if request.method == 'POST':
        form_auxilio = FormDevolucao(request.POST, instance=auxilio)
        if form_auxilio.is_valid():
            if auxilio.equipamento.emprestado:
                if auxilio.data_devolucao is None:
                    messages.error(request, 'Informe a data de devolução.')
                elif auxilio.hora_devolucao is None:
                    messages.error(request, 'Informe a hora de devolução.')
                else:
                    auxilio.equipamento.emprestado = False
                    auxilio.equipamento.save()
                    messages.success(request, 'Devolução registrada com sucesso!')
                    return redirect('pacientes:listar_equipamentos_emprestados')
            else:
                messages.error(request, 'Equipamento não estava emprestado.')
        else:
            messages.error(request, 'Erro ao validar formulário.')
    else:
        auxilio.data_devolucao = None
        form_auxilio = FormDevolucao(instance=auxilio)

    return render(request, 'auxilios/registro_devolucao.html', {'form': form_auxilio, 'auxilio': auxilio})

@assistente_social_required
@login_required
def renovar_emprestimo(request, pk):
    auxilio_antigo = get_object_or_404(Auxilio, pk=pk)
    auxilio_antigo.data_devolucao = datetime.today().strftime('%Y-%m-%d')
    auxilio_antigo.hora_devolucao = datetime.today().strftime('%H:%M:%S')

    auxilio = Auxilio()
    auxilio.tipo = auxilio_antigo.tipo
    auxilio.data_retirada = datetime.today().strftime('%Y-%m-%d')
    auxilio.hora_retirada = datetime.today().strftime('%H:%M:%S')
    auxilio.observacao = auxilio_antigo.observacao
    auxilio.quantidade = auxilio_antigo.quantidade
    auxilio.equipamento = auxilio_antigo.equipamento
    auxilio.tipo = auxilio_antigo.tipo
    auxilio.paciente = auxilio_antigo.paciente

    auxilio.save()
    auxilio_antigo.save()
    
    return redirect("/")



@login_required
def detalhes_auxilio(request, pk):
    auxilio = get_object_or_404(Auxilio, pk=pk)
    return render(request, 'auxilios/detalhes_auxilio.html', {'auxilio': auxilio})

templates/auxilios/cadastro_auxilio.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% load crispy_forms_tags %}

{% block title %}
<title>APOCA - Cadastro Auxílio</title>
{% endblock %}

{% block content %}
    {% include 'utilitarios/mensagens.html' %}

    <div class="card overflow-hidden">
        {% include 'utilitarios/cabecalho.html' with titulo='Cadastro de fornecimento de auxílio ' imagem="/static/assets/images/profile-img.png" %}

        <div class="card-body">
            {% crispy form %}
        </div>
    </div>
    {% include 'utilitarios/modal_cancelamento.html' %}
{% endblock %}
{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>
    <script src="{% static 'javascript/custom_auxilio.js' %}"></script>
{% endblock %}

templates/auxilios/detalhes_auxilio.html
{% extends 'base.html' %}
{% load static %}
{% load l10n %}


{% block title %}
    <title>APOCA - Detalhes do Auxílio</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/perfil.css' %}">
    <link rel="stylesheet" href="{% static 'assets/libs/owl.carousel/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/libs/owl.carousel/assets/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="{% static 'assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
{% endblock css %}

{% block content %}
    {% include 'utilitarios/mensagens.html' %}
    <div class="row">
    <div class="col">
            <!-- Card perfil -->
            <div class="card overflow-hidden">

                {% include 'utilitarios/cabecalho.html' with titulo='Detalhes auxílio' imagem="/static/images/SVG/auxilio_entregue.svg" %}

                <div class="card-body">
                    <div class="row">
                       
                        <div class="col-sm-12">
                            <div class="pt-2 card-perfil">
                                <h5 class="mb-0">Nome Paciente</h5>
                                <p class="text-muted mb-2">{{ auxilio.paciente.nome }}</p><br>

                                <div class="d-md-flex">
                                    <div class="d-md-block mr-md-5">
                                        <h5 class="mb-0">Tipo Auxílio</h5>
                                        <p class="text-muted mb-2">{{ auxilio.tipo }}</p><br>
                                    </div>
                                    <div class="d-md-block">
                                        <h5 class="mb-0">Quantidade</h5>
                                        <p class="text-muted mb-2">{{ auxilio.quantidade }}</p><br>
                                    </div>
                                </div>

                                <h5 class="mb-0">Data de Retirada</h5>
                                <p class="text-muted mb-2">{{ auxilio.data_retirada|date:'d/m/Y' }}</p><br>

                                <h5 class="mb-0">Hora da Retirada</h5>
                                <p class="text-muted mb-2">{{ auxilio.hora_retirada }}</p><br>

                                <h5 class="mb-0">Observação</h5>
                                <p class="text-muted mb-2">{{ auxilio.observacao }}</p><br>

                                {% if auxilio.medicamento %}
                                    <h5 class="mb-0">Medicamento</h5>
                                    <p class="text-muted mb-2">{{ auxilio.medicamento.nome }}</p><br>
                                {% endif %}

                                {% if auxilio.equipamento %}
                                    <h5 class="mb-0">Equipamento</h5>
                                    <p class="text-muted mb-2">{{ auxilio.equipamento.nome }}</p>
                                    <h5 class="mb-0">Etiqueta</h5>
                                    <p class="text-muted mb-2">{{ auxilio.equipamento.etiqueta }}</p><br>
                                    {% if auxilio.data_devolucao %}
                                    	<h5 class="mb-0">Data de Devolução</h5>
                                		<p class="text-muted mb-2">{{ auxilio.data_devolucao }}</p><br>
                                		<h5 class="mb-0">Hora da Devolução</h5>
                                		<p class="text-muted mb-2">{{ auxilio.hora_devolucao }}</p><br>
                                	{% endif %}
                                {% endif %}
                                <a href="{% url 'pacientes:listar_auxilios' %}" class="btn btn-primary">Voltar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}
{% block js %}
    <!-- owl.carousel js -->
    <script src="{% static 'assets/libs/owl.carousel/owl.carousel.min.js' %}"></script>
    <!-- timeline init js -->
    <script src="{% static 'assets/js/pages/timeline.init.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>
    <script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'javascript/perfil_paciente.js' %}"></script>

{% endblock js %}

templates/auxilios/edicao_auxilio.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% load crispy_forms_tags %}

{% block title %}
    <title>APOCA - Edição de auxílio entregue</title>
{% endblock %}

{% block content %}
    {% include 'utilitarios/mensagens.html' %}

    <div class="card overflow-hidden">
        {% include 'utilitarios/cabecalho.html' with titulo='Edição de auxílio entregue' imagem="/static/images/SVG/auxilio_entregue.svg" %}

        <div class="card-body">
            {% crispy form %}
        </div>
    </div>
    

    {% include 'utilitarios/modal_cancelamento.html' %}
{% endblock %}
{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>
    <script src="{% static 'javascript/custom_auxilio.js' %}"></script>
{% endblock %}

templates/auxilios/equipamentos_emprestados.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}
    <title>APOCA - Equipamentos emprestados</title>
{% endblock %}

{% block css %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
    {% include 'utilitarios/mensagens.html' %}

    <div class="card overflow-hidden">
        {% include 'utilitarios/cabecalho.html' with titulo="Equipamentos emprestados" imagem="/static/images/SVG/devolucao_equipamento.svg" classes="my-2" %}

        <div class="card card-body">
            <div class="table-responsive">
                <table class="table table-centered table-nowrap table-hover" id="tabela-emprestimo">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">Data empréstimo</th>
                            <th scope="col">Paciente</th>
                            <th scope="col">Etiqueta</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Quantidade</th>
                            <th scope="col">Ações</th>
                        </tr>
                    </thead>
                    <tbody id="myTable">
                        {% for auxilio in equipamentos_emprestados %}
                        <tr>
                            <td>{{ auxilio.data_retirada|date:'d/m/Y' }}</td>
                            <td>{{ auxilio.paciente.nome }}</td>
                            <td>{{ auxilio.equipamento.etiqueta }}</td>
                            <td>{{ auxilio.equipamento.nome }}</td>
                            <td>{{ auxilio.quantidade}}</td>
                            <td>
                                <ul class="list-inline font-size-20 contact-links mb-0">
                                    <li class="list-inline-item px-2">
                                        <a href="{% url 'pacientes:registrar_devolucao' pk=auxilio.pk %}" data-toggle="tooltip" data-placement="top" title="Registrar devolução"><i class="bx bx-check-circle"></i></a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Modal para a deleção -->
    {% include 'utilitarios/modal_delecao.html' %}
{% endblock %}

{% block js %}
    <script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>

    {% include 'utilitarios/configuracao_data_table.html' with tipo="emprestimo" %}

{% endblock %}

templates/auxilios/lista_auxilios.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}
    <title>APOCA - Auxílios entregues</title>
{% endblock %}

{% block css %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
{% endblock %}

{% block content %}
    {% include 'utilitarios/mensagens.html' %}

    <div class="card overflow-hidden mb-4">
        {% include 'utilitarios/cabecalho.html' with titulo="Auxílios entregues" imagem="/static/images/SVG/auxilio_entregue.svg" %}

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-centered table-nowrap table-hover" id="tabela-auxilio">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">Data</th>
                            <th scope="col">Hora</th>
                            <th scope="col">Paciente</th>
                            <th scope="col">Auxílio</th>
                            <th scope="col">Qtde</th>
                            <th scope="col">Ações</th>
                        </tr>
                    </thead>
                    <tbody id="myTable">
                        {% for auxilio in lista_auxilios %}
                        <tr>
                            <td>{{ auxilio.data_retirada|date:'d/m/Y' }}</td>
                            <td>{{ auxilio.hora_retirada }}</td>
                            <td>{{ auxilio.paciente.nome }}</td>
                            <td>{{ auxilio.tipo.nome }}</td>
                            <td>{{ auxilio.quantidade }}</td>
                            <td>
                                <ul class="list-inline font-size-20 contact-links mb-0">
                                    <li class="list-inline-item px-2">
                                        <a href="{% url 'pacientes:editar_auxilio' pk=auxilio.pk %}" data-toggle="tooltip" data-placement="top" title="Editar"><i class="bx bx-edit"></i></a>
                                    </li>
                                    <li class="list-inline-item px-2">
                                        <a href="{% url 'pacientes:detalhes_auxilio' pk=auxilio.pk %}" data-toggle="tooltip" data-placement="top" title="Detalhes"><i class="bx bx-receipt"></i></a>
                                    </li>
                                    <li class="list-inline-item px-2">
                                        <a
                                            data-toggle="tooltip"
                                            data-placement="top"
                                            title="Excluir"
                                            onclick="abrirModal({{ auxilio.pk }})"
                                        >
                                            <i class="bx bx-trash"></i>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Modal para a deleção -->
    {% include 'utilitarios/modal_delecao.html' %}
{% endblock %}

{% block js %}
    {% include 'utilitarios/configuracao_data_table.html' with tipo="auxilio" %}

    <script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>



{% endblock %}

templates/auxilios/registro_devolucao.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock %}

{% load crispy_forms_tags %}

{% block title %}
    <title>APOCA - Devolução de equipamento</title>
{% endblock %}

{% block content %}
    {% include 'utilitarios/mensagens.html' %}

    <div class="card overflow-hidden">
        {% include 'utilitarios/cabecalho.html' with titulo="Devolução de equipamento" imagem="/static/images/SVG/devolucao_equipamento.svg" classes="my-2" %}

        <div class="card-body">
            <h2 class="mb-3 ml-md-2">Detalhes sobre o empréstimo</h2>
            <div class="d-md-flex mt-4">
                <div class="col-md-3">
                    <p class="text-muted mb-0">Paciente</p>
                    <h6>{{ auxilio.paciente.nome }}</h6>
                </div>
                <div class="col-md-3">
                    <p class="text-muted mb-0">Equipamento</p>
                    <h6>{{ auxilio.equipamento.nome }}</h6>
                </div>
                <div class="col-md-3">
                    <p class="text-muted mb-0">Etiqueta</p>
                    <h6>{{ auxilio.equipamento.etiqueta }}</h6>
                </div>
            </div>
            <div class="d-md-flex mb-4">
                <div class="col-md-3">
                    <p class="text-muted mb-0">Data de retirada</p>
                    <h6>{{ auxilio.data_retirada|date:'d/m/Y' }}</h6>
                </div>
                <div class="col-md-3">
                    <p class="text-muted mb-0">Horário de retirada</p>
                    <h6>{{ auxilio.hora_retirada|date:'H:i' }}</h6>
                </div>
                <div class="col-md-3">
                    <p class="text-muted mb-0">Quantidade</p>
                    <h6 class="mb-3">{{ auxilio.quantidade }}</h6>
                </div>
            </div>

            {% crispy form %}
        </div>
    </div>

    {% include 'utilitarios/modal_cancelamento.html' %}
{% endblock %}

{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>
    <script src="{% static 'javascript/devolucao.js' %}"></script>
{% endblock %}