apoca/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from pacientes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # TODO: remover linha abaixo apos criar sistema de login completo
    path('accounts/login/', auth_views.LoginView.as_view(template_name='admin/login.html')),
    path('accounts/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pacientes.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pacientes/urls.py
from django.urls import path
from . import views

app_name = 'pacientes'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('pacientes/', views.pacientes, name='pacientes'),
    path('paciente/cadastrar/', views.cadastrar_paciente, name='cadastrar_paciente'),
    path('paciente/<int:pk>/editar/', views.editar_paciente, name='editar_paciente'),
    path('paciente/<int:pk>/perfil_paciente', views.perfil_paciente, name='perfil_paciente'),
    path('paciente/<int:pk>/consultas/cadastrar/', views.cadastrar_consulta, name='cadastrar_consulta'),
    path('paciente/<int:pk>/consultas/editar/', views.editar_consulta, name='editar_consulta'),
    path('paciente/<int:pk>/exames/cadastrar/', views.cadastrar_exame, name='cadastrar_exame'),
    path('paciente/<int:pk>/exames/editar/', views.editar_exame, name='editar_exame'),
    path('paciente/<int:pk>/auxilio/cadastrar/', views.cadastrar_auxilio, name='cadastrar_auxilio'),
    path('paciente/<int:pk>/auxilio/editar/', views.editar_auxilio, name='editar_auxilio'),

    path('auxilios/', views.listar_auxilios, name='listar_auxilios'),
    path('auxilios/equipamentos_emprestados', views.listar_equipamentos_emprestados, name='listar_equipamentos_emprestados'),
    path('auxilios/<int:pk>/registrar_devolucao', views.registrar_devolucao, name='registrar_devolucao'),
    path('auxilios/<int:pk>/renovar_emprestimo', views.renovar_emprestimo, name='renovar_emprestimo'),
    path('auxilios/<int:pk>/detalhes_auxilio', views.detalhes_auxilio, name='detalhes_auxilio'),

    # URLS ajax
    path('paciente/<int:pk>/remover_foto', views.remover_foto, name='remover_foto'),
    path('paciente/<int:pk>/filtrar_auxilios', views.filtrar_auxilios, name='filtrar_auxilios'),
    path('filtrar_info_gerais/', views.filtrar_info_gerais, name='filtrar_info_gerais'),

    # URL administrativo
    path('administrativo/', views.administrativo, name='administrativo'),
    path('administrativo/backup/', views.backup, name='backup'),

    # URL apresentação equipe
    path('equipe/', views.equipe, name='equipe'),

    # Cadastros gerais
    path('cadastros-gerais/medicamento/', views.medicamentos, name='medicamentos'),
    path('cadastros-gerais/medicamento/cadastrar/', views.cadastrar_medicamento, name='cadastrar_medicamento'),
    path('cadastros-gerais/medicamento/<int:pk>/editar/', views.editar_medicamento, name='editar_medicamento'),
    path('cadastros-gerais/equipamento/', views.equipamentos, name='equipamentos'),
    path('cadastros-gerais/equipamento/cadastrar/', views.cadastrar_equipamento, name='cadastrar_equipamento'),
    path('cadastros-gerais/equipamento/<int:pk>/editar/', views.editar_equipamento, name='editar_equipamento'),
    path('cadastros-gerais/tipo-auxilio/', views.tipos_auxilios, name='tipos_auxilios'),
    path('cadastros-gerais/tipo-auxilio/cadastrar/', views.cadastrar_tipo_auxilio, name='cadastrar_tipo_auxilio'),
    path('cadastros-gerais/tipo-auxilio/<int:pk>/editar/', views.editar_tipo_auxilio, name='editar_tipo_auxilio'),
    path('cadastros-gerais/cidade/', views.cidades, name='cidades'),
    path('cadastros-gerais/cidade/cadastrar/', views.cadastrar_cidade, name='cadastrar_cidade'),
    path('cadastros-gerais/cidade/<int:pk>/editar/', views.editar_cidade, name='editar_cidade'),
    path('cadastros-gerais/tipo-consulta/', views.tipos_consulta, name='tipos_consulta'),
    path('cadastros-gerais/tipo-consulta/cadastrar/', views.cadastrar_tipo_consulta, name='cadastrar_tipo_consulta'),
    path('cadastros-gerais/tipo-consulta/<int:pk>/editar/', views.editar_tipo_consulta, name='editar_tipo_consulta'),
    path('cadastros-gerais/doenca/', views.doencas, name='doencas'),
    path('cadastros-gerais/doenca/cadastrar/', views.cadastrar_doenca, name='cadastrar_doenca'),
    path('cadastros-gerais/doenca/<int:pk>/editar/', views.editar_doenca, name='editar_doenca'),
    path('cadastros-gerais/suplemento-alimentar/', views.sup_alimentares, name='sup_alimentares'),
    path('cadastros-gerais/suplemento-alimentar/cadastrar/', views.cadastrar_sup_alimentar, name='cadastrar_sup_alimentar'),
    path('cadastros-gerais/suplemento-alimentar/<int:pk>/editar/', views.editar_sup_alimentar, name='editar_sup_alimentar'),

    # Consulta
    path('consultas/', views.consultas, name='consultas'),

    # Exame
    path('exames/', views.exames, name='exames'),
]

pacientes/models.py
from django.db import models
from django.conf import settings
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.validators import MinValueValidator

from PIL import Image
from io import BytesIO
import sys


class Paciente(models.Model):
    SEXO_CHOICES = (
        ('Masculino', 'Masculino'),
        ('Feminino', 'Feminino'),
        ('Outro', 'Outro'),
        ("nulo", "nulo")
    )

    RACA_CHOICES = (
        ('Branca', 'Branca'),
        ('Preta', 'Preta'),
        ('Parda', 'Parda'),
        ('Amarela', 'Amarela'),
        ('Indígena', 'Indígena'),
        ('Não informado', 'Não informado')
    )

    foto = models.ImageField(blank=True, null=True, upload_to='fotos/%Y/')
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    # Dados Gerais
    nome = models.CharField(max_length=150)
    sexo = models.CharField(max_length=15, choices=SEXO_CHOICES, default='Masculino')
    data_nascimento = models.DateField('Data de nascimento')
    raca = models.CharField('Raça', max_length=20, choices=RACA_CHOICES, default='Não informado')
    cpf = models.CharField('CPF', max_length=14)
    rg = models.CharField('RG', max_length=9)
    orgao_expedidor = models.CharField('Orgão expedidor', max_length=300, blank=True, null=True)
    cartao_sus = models.CharField('Cartão SUS', max_length=20, blank=True, null=True)
    nome_mae = models.CharField('Nome da mãe', max_length=150)
    conjuge = models.CharField('Cônjuge', max_length=150, blank=True, null=True)
    # Financeiro e Familiar
    profissao = models.CharField('Profissão', max_length=50, blank=True, null=True)
    casa_propria = models.BooleanField('Casa própria', default=False)
    outros_casos = models.BooleanField(default=False)
    composicao_familiar = models.PositiveIntegerField('Composição familiar')
    renda_familiar = models.FloatField('Renda familiar', default=0, validators=[MinValueValidator(0)])
    vulnerabilidade_social = models.BooleanField('Vulnerabilidade social', default=False)
    observacao_renda = models.CharField('Observação', max_length=300, blank=True, null=True) 
    # Doenca
    doenca = models.ForeignKey('Doenca', on_delete=models.PROTECT, verbose_name='Diagnóstico')
    metastase = models.BooleanField('Metástase', default=False)
    descricao_metastase = models.CharField('Localização metástase', max_length=200, blank=True, null=True)
    diabetes = models.BooleanField(default=False)
    referencia_doenca = models.CharField('Referência hospitalar', max_length=150, default='')
    # Endereco
    logradouro = models.CharField(max_length=100)
    numero = models.PositiveIntegerField('Número', blank=True, null=True, validators=[MinValueValidator(0)])
    bairro = models.CharField(max_length=50)
    cidade = models.ForeignKey('Cidade', on_delete=models.PROTECT)
    cep = models.CharField('CEP', max_length=9)
    complemento = models.CharField(max_length=50, blank=True, null=True)
    referencia = models.CharField('Ponto de referência', max_length=200, blank=True, null=True)
    # Demais informacoes
    ativo = models.BooleanField(default=True)
    data_cadastro = models.DateField('Data de cadastro')
    tipo_auxilio_aprovado = models.ManyToManyField('pacientes.TipoAuxilio', blank=True)
    paciente = models.BooleanField(default=True)
    comodatario = models.BooleanField(default=False)

    def __str__(self):
        return self.nome

    def save(self, *args, **kwargs):
        if self.foto:
            im = Image.open(self.foto)
            output = BytesIO()
            im.thumbnail((512, 512), Image.ANTIALIAS)

            im.save(output, format='JPEG', quality=80)
            output.seek(0)

            self.foto = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.foto.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)

        super(Paciente, self).save()

    def renda_per_capita(self):
        return self.renda_familiar / self.composicao_familiar

    def converter_renda_familiar(self, renda):
        renda = renda.replace('.', '').replace(',', '.')
        self.renda_familiar = float(renda)


class Doenca(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ['nome']


class Cidade(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ['nome']


class Telefone(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, related_name='telefones')
    ddd = models.CharField(max_length=3)
    telefone = models.CharField(max_length=9)

    def __str__(self):
        return ('({}) {}' .format(self.ddd, self.telefone))


class Responsavel(models.Model):
    paciente = models.ForeignKey("Paciente", on_delete=models.CASCADE)
    nome = models.CharField(max_length=200)

    def __str__(self):
        return self.nome

    class Meta():
        verbose_name_plural = 'responsáveis'


class Medicamento(models.Model):
    nome = models.CharField(max_length=200, blank=False, null=False)

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ['nome']


class Equipamento(models.Model):
    etiqueta = models.CharField(max_length=50, blank=True, null=True)
    nome = models.CharField(max_length=200, blank=False, null=False)
    emprestado = models.BooleanField(blank=False, null=False, default=False)
    quantidade = models.IntegerField(blank=False, null=False, default=0)

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ['nome']

class SuplementoAlimentar(models.Model):
    nome = models.CharField(max_length=200, blank=False, null=False)

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ['nome']

class TipoAuxilio(models.Model):
    nome = models.CharField(max_length=200, blank=False, null=False)
    abreviacao = models.CharField('Abreviação', max_length=5, blank=False, null=False)

    def __str__(self):
        return self.nome


class Auxilio(models.Model):
    tipo = models.ForeignKey(TipoAuxilio, on_delete=models.PROTECT)
    data_retirada = models.DateField(blank=False, null=False)
    hora_retirada = models.TimeField(blank=True, null=True)
    observacao = models.TextField(max_length=1000, blank=True, null=True, verbose_name='Observações')
    quantidade = models.PositiveIntegerField(blank=False, null=False, validators=[MinValueValidator(1)])
    medicamento = models.ForeignKey(Medicamento, on_delete=models.PROTECT,
        blank=True, null=True, default=None, related_name='medicamentos')
    equipamento = models.ForeignKey(Equipamento, on_delete=models.PROTECT,
        blank=True, null=True, default=None, related_name='equipamentos')
    suplemento_alimentar = models.ForeignKey(SuplementoAlimentar, on_delete=models.PROTECT,
        blank=True, null=True, default=None, related_name='suplementos')
    data_devolucao = models.DateField(blank=True, null=True, verbose_name='Data Devolução')
    hora_devolucao = models.TimeField(blank=True, null=True, verbose_name='Hora Devolução')
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT,
        blank=True, null=True, default=None, related_name='auxilios')

    def __str__(self):
        if self.medicamento:
            return f'{self.tipo.nome} ({self.medicamento})'
        elif self.equipamento:
            return f'{self.tipo.nome} ({self.equipamento})'
        elif self.suplemento_alimentar:
            return f'{self.tipo.nome} ({self.suplemento_alimentar})'
        else:
            return f'{self.tipo.nome}'


class TipoConsulta(models.Model):
    nome = models.CharField(max_length=200, blank=False, null=False)

    def __str__(self):
        return self.nome


class Consulta(models.Model):
    tipo = models.ForeignKey(TipoConsulta, on_delete=models.PROTECT)
    data = models.DateField(blank=False, null=False)
    observacao = models.TextField(blank=True, null=True)
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.tipo.nome} - ({self.paciente})'


class Exame(models.Model):
    tipo = models.CharField(max_length=250, blank=False, null=False)
    data = models.DateField(blank=False, null=False)
    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.tipo} - ({self.paciente})'

pacientes/views/administrativo.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages

from ..decorators import *
from multiprocessing import Process
import os
import datetime
import time
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive


@assistente_social_required
@login_required
def administrativo(request):
    return render(request, 'administrativo/administrativo.html')


@assistente_social_required
@login_required
def backup(request):
    try:
        p = Process(target=criar_backup)
        p.start()
    except Exception:
        messages.error(request, 'Erro ao realizar backup. Tente novamente em alguns instantes.')
    else:
        messages.success(request, 'O processo de backup foi agendado e será realizado assim que possível. Aguarde alguns instantes.')

    return redirect('pacientes:administrativo')


def criar_backup():
    dir = os.path.join(settings.BASE_DIR, 'backups/{}'.format(datetime.date.today().year))
    if not os.path.exists(dir):
        os.makedirs(dir)
    agora = datetime.datetime.now().strftime('%Y-%m-%d-%H:%M:%S')
    nome = '{}-backup.sql.gz'.format(agora)
    arquivo = os.path.join(dir, nome)
    os.system(f'mysqldump -h {settings.DB_HOST} -u {settings.DB_USER} -p\'{settings.DB_PASSWORD}\' \'{settings.DB_NAME}\' | gzip -9 -c > {arquivo}')
    # Drive autenticacao
    gauth = GoogleAuth()
    try:
        gauth.LoadCredentialsFile('mycreds.txt')
    except Exception:
        pass
    else:
        gauth.LocalWebserverAuth()
        gauth.SaveCredentialsFile('mycreds.txt')

    drive = GoogleDrive(gauth)
    # Upload arquivo
    file = drive.CreateFile({'parents': [{'id': '1Fd1xTGtZAN4PwUgzLxjYeJmrKJmjc2nd'}]})
    file.SetContentFile(arquivo)
    file['title'] = nome
    file.Upload()
    # Remove arquivo local
    time.sleep(5)
    os.remove(arquivo)

pacientes/views/consultas.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from ..decorators import *
from ..models import Consulta, Paciente
from ..forms import FormConsulta


@assistente_social_required
@login_required
def consultas(request):
    consultas = Consulta.objects.all().order_by('-data')

    return render(request, 'consulta/consulta.html', {'consultas': consultas})


@assistente_social_required
@login_required
def cadastrar_consulta(request, pk):
    paciente = get_object_or_404(Paciente, pk=pk)
    form = FormConsulta(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            consulta = form.save(commit=False)
            consulta.paciente = paciente
            consulta.save()

            messages.success(request, 'Consulta cadastrada com sucesso.')
            return redirect('pacientes:perfil_paciente', pk=consulta.paciente.pk)

        messages.error(request, 'Não foi possível cadastrar a consulta.')
    return render(request, 'consulta/cadastro_consulta.html', {'form': form, 'paciente': paciente})


@assistente_social_required
@login_required
def editar_consulta(request, pk):
    consulta = get_object_or_404(Consulta, pk=pk)

    if request.method == 'POST':
        form = FormConsulta(request.POST, instance=consulta)
        if form.is_valid():
                form.save()
                messages.success(request, 'Consulta editada com sucesso!')
                return redirect('pacientes:perfil_paciente', pk=consulta.paciente.id)

        messages.error(request, 'Não foi possível editar a consulta.')
    else:
        form = FormConsulta(instance=consulta)

    return render(request, 'consulta/edicao_consulta.html', {'form': form, 'paciente': consulta.paciente})

pacientes/views/equipe.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def equipe(request):
    return render(request, 'pacientes/equipe_desenvolvimento.html')

templates/pacientes/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>APOCA - Home</title>
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/libs/chart.js/Chart.min.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock %}

{% block content %}
<input type="hidden" id="url-filtro" value="{% url 'pacientes:filtrar_info_gerais' %}">

<div class="row">
  <div class="col-lg-12">
    {% include 'utilitarios/mensagens.html' %}
    <div class="card card-body">
      <div class="align-self-center container">
        <div class="mt-4 mt-lg-0">
          <h1 class="text-center mb-3">Informações gerais</h1>

          <!-- <p class="text-muted font-weight-medium mb-1">Filtros</p> -->
          <div class="d-md-flex justify-content-center">
              <div class="col-lg-3 col-xl-2 pl-0 mb-3">
                <label for="data-inicio" class="text-muted mb-0">De</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text">
                          <i class="bx bx-calendar"></i>
                      </span>
                    </div>
                    <input type="text" id="data-inicio" class="form-control" value="{{ data_inicio|date:'d/m/Y' }}">
                </div>
              </div>
              <div class="col-lg-3 col-xl-2 pl-0 mb-3">
                <label for="data-fim" class="text-muted mb-0">Até</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                      <span class="input-group-text">
                          <i class="bx bx-calendar"></i>
                      </span>
                    </div>
                    <input type="text" id="data-fim" class="form-control">
                </div>
              </div>

              <div class="col-md-3 pl-0 mb-3">
                <label for="cidade" class="text-muted mb-0">Cidade</label>
                <select name="cidade" id="cidade" class="form-control">
                  <option value="Total" selected>Total</option>
                  {% for cidade in cidades %}
                    <option value="{{ cidade.nome }}">{{ cidade.nome }}</option>
                  {% endfor %}
                </select>
              </div>
          </div>

          <hr class="mt-1 mb-4" />
          <div class="d-flex justify-content-center mb-3">
            <div class="col-md-3 text-center">
              <p class="card-title mb-2">Pacientes no sistema</p>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col-md-3 text-center">
              <div>
                <p class="text-muted mb-2">Ativos</p>
                <h5 class="text-success" id="paciente-ativo"></h5>
              </div>
            </div>
            <div class="col-md-3 text-center">
              <div>
                <p class="text-muted mb-2">Inativos</p>
                <h5 class="text-danger" id="paciente-inativo"></h5>
              </div>
            </div>
            <div class="col-md-3 text-center">
              <div>
                <p class="text-muted mb-2">Total</p>
                <h5 class="text-primary" id="paciente-total"></h5>
              </div>
            </div>
          </div>

          <hr class="mt-4 mb-4" />
          <div class="d-flex justify-content-center mb-3">
            <div class="col-md-3 text-center">
              <p class="card-title mb-2">Auxílios entregues</p>
            </div>
          </div>
          <div class="row justify-content-center" id="tipo_auxilios">
            <!--Auxilios entregues-->
          </div>

          <hr class="mt-4 mb-4" />
          <div class="d-flex justify-content-center mb-3">
            <div class="col-md-3 text-center">
              <p class="card-title mb-2">Consultas e exames</p>
            </div>
          </div>

          <div class="row justify-content-center">
            <div class="col-md-3 text-center">
              <div>
                <p class="text-muted mb-2">Consultas</p>
                <h5 class="mb-3" id="consulta"></h5>
              </div>
            </div>
            <div class="col-md-3 text-center">
              <div>
                <p class="text-muted mb-2">Exames</p>
                <h5 class="mb-3" id="exame"></h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <div class="card card-body">
      <h4 class="text-center">Últimos pacientes cadastrados</h4>

      <div class="table-responsive mt-3">
        <table class="table table-centered table-nowrap table-hover mb-0">
          <thead class="thead-light">
            <tr>
                <th></th>
                <th scope="col">Nome</th>
                <th scope="col">Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for paciente in pacientes %}
              <tr>
                <td>
                  {% if paciente.foto %}
                    <img src="{{ paciente.foto.url }}" alt="{{ paciente.nome }}" class="rounded-circle avatar-xs">
                  {% else %}
                    <img src="{% static 'assets/images/users/user-img.png' %}" alt="Imagem usuário" class="rounded-circle avatar-xs">
                  {% endif %}
                </td>
                <td>
                  <p class="mb-0">{{ paciente.nome|truncatechars:20 }}</p>
                </td>
                <td>
                  <ul class="list-inline font-size-20 contact-links mb-0">
                    {% if user.is_assistente_social %}
                      <li class="list-inline-item px-1 mb-2">
                          <a href="{% url 'pacientes:editar_paciente' pk=paciente.pk %}" data-toggle="tooltip" data-placement="top" title="Editar"><i class="bx bx-edit"></i></a>
                      </li>
                    {% endif %}
                    <li class="list-inline-item px-1">
                        <a href="{% url 'pacientes:perfil_paciente' pk=paciente.pk %}" data-toggle="tooltip" data-placement="top" title="Perfil"><i class="bx bx-user-circle"></i></a>
                    </li>
                  </ul>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

    </div>
  </div>

  <div class="col-lg-8">
    <div class="card card-body text-center">
      <h4 class="mb-4">Atividades diárias</h4>

      <div class="d-md-flex justify-content-around">
        <div>
          <p class="text-muted mb-3">Pacientes cadastrados</p>
          <h5 class="mb-3">{{ atv_diaria.pacientes }}</h5>
        </div>
        <div>
          <p class="text-muted mb-3">Auxílios entregues</p>
          <h5 class="mb-3">{{ atv_diaria.auxilios }}</h5>
        </div>
        <div>
          <p class="text-muted mb-3">Consultas realizadas</p>
          <h5 class="mb-3">{{ atv_diaria.consultas }}</h5>
        </div>
        <div>
          <p class="text-muted mb-3">Exames cadastrados</p>
          <h5 class="mb-3">{{ atv_diaria.exames }}</h5>
        </div>
      </div>
    </div>

    <div class="card card-body">
      <canvas id="grafico-etnias"></canvas>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-lg-12">
    <div class="card card-body">
      <h4 class="text-center">Emprestimos vencidos</h4>

      <div class="table-responsive mt-3">
        <table class="table table-centered table-nowrap table-hover mb-0">
          <thead class="thead-light">
            <tr>
                <th>Data</th>
                <th scope="col">nome Paciente</th>
                <th scope="col">Equipamento</th>
                <th scope="col">Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for equipamento in equipamentosAuxilio %}
              <tr>
                <td>
                  {{ equipamento.data_retirada }}
                </td>
                <td>
                  <a href="{% url 'pacientes:perfil_paciente' pk=equipamento.paciente.pk %}">{{ equipamento.paciente.nome }}</a>
                </td>
                <td>
                  {{ equipamento.equipamento.nome }}
                </td>
                <td>
                  
                  <h3><a class="ml-1" href="{% url 'pacientes:registrar_devolucao' pk=equipamento.pk %}" data-toggle="tooltip" data-placement="top" title="Registrar devolução"><i class="bx bx-check-circle"></i></a> <a href="{% url 'pacientes:renovar_emprestimo' pk=equipamento.pk %}" data-toggle="tooltip" data-placement="top" title="Renovar Empréstimo"><i class="fas fa-exchange-alt"></i></a></h3>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

    </div>
  </div>
{% endblock %}

{% block js %}
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>
  <script src="{% static 'assets/libs/chart.js/Chart.min.js' %}"></script>
  <script src="{% static 'javascript/home.js' %}"></script>

  <script>
    var tema = sessionStorage.getItem('is_visited');
    var cor = (tema == 'dark-mode-switch') ? '#fff' : '#333';
    Chart.defaults.global.defaultFontColor = cor;
    var ctx = document.getElementById('grafico-etnias');
    var graficoEtnia = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['Branca', 'Preta', 'Parda', 'Amarela', 'Indígena', 'Não informado'],
            datasets: [{
                label: 'Raças',
                data: [
                  {% for raca in racas %}
                      {{ raca }},
                  {% endfor %}
                ],
                backgroundColor: [
                    'rgba(115, 43, 237, 0.8)',
                    'rgba(65, 45, 247, 0.8)',
                    'rgba(52, 82, 225, 0.8)',
                    'rgba(45, 132, 247, 0.8)',
                    'rgba(153, 102, 255, 0.8)',
                    'rgba(43, 177, 237, 0.8)',
                    'rgba(115, 43, 237, 0.8)',
                    'rgba(65, 45, 247, 0.8)',
                ],
                borderWidth: 0
            }]
        },
        options: {
            scales: {
                xAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
  </script>
{% endblock %}